version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: bridge
    depends_on:
      - php
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker-configs/Dockerfile
    volumes:
      - ./:/var/www/html:delegated
      - ./docker-configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "9000:9000"
    network_mode: bridge
    external_links:
      - mysql
