version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-volume-57:/var/lib/mysql:delegated
      - ./docker-configs:/tmp
    network_mode: bridge
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-data:/data:cached
    ports:
      - "6379:6379"
    network_mode: bridge
volumes:
  mysql-volume-57:
  redis-data:
